name: Build

on:
  push:
    branches:
    - v2

env:
  # 设置 docker 镜像名
  IMAGE_NAME: fasttunnel-v2

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v1
   - name: Setup .NET Core
     uses: actions/setup-dotnet@v1
     with:
       dotnet-version: 7.0.*
       include-prerelease: true
   - name: Build with dotnet
     run: chmod +x ./publish.sh && ./publish.sh
