name: Build

on: [push]
env:
  # 设置 docker 镜像名
  IMAGE_NAME: fasttunnel

jobs:
  publish:
    name: publish-core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
           dotnet-version: 7.0.x

      # Publish
      - name: publish on version change
        id: publish_nuget
        uses: SpringHgui/publish-nuget@1.0.1
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: FastTunnel.Core/FastTunnel.Core.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
  hosting:
    name: publish-hosting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
           dotnet-version: 7.0.x

      # Publish
      - name: publish on version change
        id: publish_nuget
        uses: SpringHgui/publish-nuget@1.0.1
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: FastTunnel.Hosting/FastTunnel.Hosting.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
  api:
    name: publish-api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
           dotnet-version: 7.0.x

      # Publish
      - name: publish on version change
        id: publish_nuget
        uses: SpringHgui/publish-nuget@1.0.1
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: FastTunnel.Api/FastTunnel.Api.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
  docker:
    name: publish-docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # 构建镜像，指定镜像名
      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME
        # 登录到 dockerhub，使用 GitHub secrets 传入账号密码，密码被加密存储在 GitHub 服务器，添加方法见下图。
      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u springhgui --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=springhgui/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          # 设置镜像 id 和版本号
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          # 进行 push
          docker push $IMAGE_ID:$VERSION
